version: 1

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: /flight-tracker/logs/log.log
        mode: w+

root:
    level: INFO
    handlers: [file_handler]